packages:
  - packages/client
  - packages/lodash3
  - packages/pathfinder
  - packages/redis
  - packages/xxscreeps

allowBuilds:
  isolated-vm: true
  ivm-inspect: true

minimumReleaseAgeExclude:
  - '@auto_js/*'
  - '@isolated-vm/*'
  - '@xxscreeps/pathfinder-darwin-arm64'
  - '@xxscreeps/pathfinder-darwin-x64'
  - '@xxscreeps/pathfinder-linux-arm64-gnu'
  - '@xxscreeps/pathfinder-linux-arm64-musl'
  - '@xxscreeps/pathfinder-linux-x64-gnu'
  - '@xxscreeps/pathfinder-linux-x64-musl'
  - '@xxscreeps/pathfinder-win32-x64'
  - '@xxscreeps/pathfinder'

patchedDependencies:
  lodash-es: patches/lodash-es.patch

storeDir: ./.pnpm-store
