packages:
  - packages/client
  - packages/lodash3
  - packages/pathfinder
  - packages/redis
  - packages/xxscreeps

allowBuilds:
  isolated-vm: true
  ivm-inspect: true

minimumReleaseAgeExclude:
  - '@auto_js/*'
  - '@isolated-vm/*'
  - '@xxscreeps/pathfinder-darwin-arm64@0.4.3'
  - '@xxscreeps/pathfinder-darwin-x64@0.4.3'
  - '@xxscreeps/pathfinder-linux-arm64-gnu@0.4.3'
  - '@xxscreeps/pathfinder-linux-arm64-musl@0.4.3'
  - '@xxscreeps/pathfinder-linux-x64-gnu@0.4.3'
  - '@xxscreeps/pathfinder-linux-x64-musl@0.4.3'
  - '@xxscreeps/pathfinder-win32-x64@0.4.3'
  - '@xxscreeps/pathfinder@0.4.3'

patchedDependencies:
  lodash-es: patches/lodash-es.patch

storeDir: ./.pnpm-store
