packages:
  - packages/client
  - packages/lodash3
  - packages/pathfinder
  - packages/redis
  - packages/xxscreeps

allowBuilds:
  isolated-vm: true
  ivm-inspect: true

patchedDependencies:
  lodash-es: patches/lodash-es.patch

storeDir: ./.pnpm-store
