#!/bin/sh
NEXT=
NODE_ARGS=()
SCRIPT_ARGS=()
while (( "$#" )); do
	if [[ "$NEXT" ]]; then SCRIPT_ARGS+=("$1");
	elif [[ "$1" = -* ]]; then NODE_ARGS+=("$1");
	else NEXT=1; continue; fi
	shift
done

BASE=$(dirname "$(realpath $0)")
exec node "${NODE_ARGS[@]}" \
	--enable-source-maps \
	--experimental-specifier-resolution=node \
	--experimental-import-meta-resolve \
	--experimental-repl-await \
	--stack-trace-limit=20 \
	"$BASE"/dist/config/entry "${SCRIPT_ARGS[@]}"
