declare module 'xxscreeps:mods/constants' {
	export * from 'xxscreeps/mods/chemistry/constants.js';
	export * from 'xxscreeps/mods/combat/constants.js';
	export * from 'xxscreeps/mods/construction/constants.js';
	export * from 'xxscreeps/mods/controller/constants.js';
	export * from 'xxscreeps/mods/creep/constants.js';
	export * from 'xxscreeps/mods/defense/constants.js';
	export * from 'xxscreeps/mods/factory/constants.js';
	export * from 'xxscreeps/mods/flag/constants.js';
	export * from 'xxscreeps/mods/harvestable/constants.js';
	export * from 'xxscreeps/mods/invader/constants.js';
	export * from 'xxscreeps/mods/logistics/constants.js';
	export * from 'xxscreeps/mods/market/constants.js';
	export * from 'xxscreeps/mods/mineral/constants.js';
	export * from 'xxscreeps/mods/nuker/constants.js';
	export * from 'xxscreeps/mods/observer/constants.js';
	export * from 'xxscreeps/mods/resource/constants.js';
	export * from 'xxscreeps/mods/road/constants.js';
	export * from 'xxscreeps/mods/source/constants.js';
	export * from 'xxscreeps/mods/spawn/constants.js';
	export * from 'xxscreeps/mods/structure/constants.js';
}
