declare module 'xxscreeps:mods/constants' {
	export * from 'xxscreeps/mods/classic/brokerage/constants.js';
	export * from 'xxscreeps/mods/classic/chemistry/constants.js';
	export * from 'xxscreeps/mods/classic/combat/constants.js';
	export * from 'xxscreeps/mods/classic/construction/constants.js';
	export * from 'xxscreeps/mods/classic/controller/constants.js';
	export * from 'xxscreeps/mods/classic/creep/constants.js';
	export * from 'xxscreeps/mods/classic/defense/constants.js';
	export * from 'xxscreeps/mods/classic/harvestable/constants.js';
	export * from 'xxscreeps/mods/classic/logistics/constants.js';
	export * from 'xxscreeps/mods/classic/mineral/constants.js';
	export * from 'xxscreeps/mods/classic/resource/constants.js';
	export * from 'xxscreeps/mods/classic/road/constants.js';
	export * from 'xxscreeps/mods/classic/source/constants.js';
	export * from 'xxscreeps/mods/classic/spawn/constants.js';
	export * from 'xxscreeps/mods/classic/structure/constants.js';
	export * from 'xxscreeps/mods/invader/constants.js';
	export * from 'xxscreeps/mods/meta/flag/constants.js';
	export * from 'xxscreeps/mods/modern/factory/constants.js';
	export * from 'xxscreeps/mods/modern/nuker/constants.js';
	export * from 'xxscreeps/mods/modern/observer/constants.js';
}
