#!/bin/sh
export CXXFLAGS="-isystem/Library/Developer/CommandLineTools/usr/include/c++/v1
-isystem/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
-isystem/Library/Developer/CommandLineTools/usr/include
-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
/usr/bin/python $(~/node_modules/.bin/node-gyp configure --release 2>&1 | grep 'spawn args' | cut -c23- | perl -pe "s/'(.+)',?/\1/;" -pe 's/^make$/compile_commands_json/;' -pe 's/\s+\]$//')
JSON=Release/compile_commands.json
for FLAG in $CXXFLAGS; do
	FLAG=$(echo "$FLAG" | perl -pe 's/\//\\\//g')
	cat $JSON | perl -pe 's/ -c / '$FLAG' -c /;' > .json.tmp
	mv .json.tmp $JSON
done
mv $JSON ./
rm -rf Common Debug Optimized Profile
rmdir Release
