name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm explore @xxscreeps/path-finder -- npm install
      - run: npm run build
      - run: npm test
