name: xxscreeps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-release:
    name: Build, Test, Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      # Setup
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      # Build & test
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test

      # Publish to npm
      - if: github.repository == 'laverdet/xxscreeps' && github.ref_name == 'main' && github.event_name == 'push'
        id: publish
        shell: sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish --filter '!@xxscreeps/pathfinder' --no-git-checks --provenance --recursive
      - if: steps.publish.outcome == 'skipped'
        shell: sh
        run: pnpm publish --dry-run --filter '!@xxscreeps/pathfinder' --no-git-checks

      # Open version package PR. Do this last because it modifies package.json in all monorepo
      # packages, which would cause the above 'pnpm publish' command to go wild.
      - if: steps.publish.outcome == 'success'
        uses: changesets/action@v1
        with:
          createGithubReleases: false
